update error message to newer command name

diff --git a/tlp-functions.in b/tlp-functions.in
--- a/tlp-functions.in
+++ b/tlp-functions.in
@@ -2545,7 +2545,7 @@ save_charge_thresholds () { # save current thresholds in $THRESHSAVEFILE
         touch $THRESHSAVEFILE
         echo $st $sp $bat_str | sort -u -k 3,3 - $THRESHSAVEFILE -o $THRESHSAVEFILE
     else
-        echo "Error: setchargeonce function not available for this ThinkPad model." 1>&2
+        echo "Error: setchargewhileac function not available for this ThinkPad model." 1>&2
         return 1
     fi
 }
